//! The private-stamp test vectors in `test-vectors/private.json`: seals, receipts and records that the
//! TypeScript side (the site, the verifier) must reproduce byte for byte.
//!
//! Regenerate with: `cargo test --features private --test vectors_private -- --ignored --nocapture`
#![cfg(feature = "private")]

use base64::Engine;
use serde_json::{json, Value};
use stamper_core::private::memo::Receipt;
use stamper_core::private::seal::{seal, RequestKey};
use stamper_core::record::record_v2;

fn vectors() -> Value {
    let b64 = |b: &[u8]| base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(b);
    let mut seals = Vec::new();
    for (i, (rk, kid, holder, receiver, esk)) in [([1u8; 32], 1u8, [2u8; 32], [3u8; 43], [4u8; 32]), ([0x11; 32], 7, [0x22; 32], [0x33; 43], [0x44; 32]), ([0xa5; 32], 255, [0; 32], [0xff; 43], [0x5a; 32])].into_iter().enumerate() {
        let k = RequestKey::from_bytes(rk);
        let s = seal(&k.public(), kid, &holder, &receiver, esk).unwrap();
        seals.push(json!({
            "case": i,
            "requestSecret": hex::encode(rk),
            "requestPublic": hex::encode(k.public()),
            "kid": kid,
            "holder": bs58::encode(holder).into_string(),
            "receiver": hex::encode(receiver),
            "esk": hex::encode(esk),
            "sealed": b64(&s),
            "memo": format!("sapling-stamp:2:{kid}:{}", b64(&s)),
        }));
    }
    let receipts: Vec<Value> = [
        Receipt { ticker: "ROOT".into(), mint: bs58::encode([5u8; 32]).into_string(), burned: 1_250_000_000_000, harvested: 1_234_567, fee: 40_000, signature: bs58::encode([9u8; 64]).into_string(), block_time: 1_790_424_000 },
        Receipt { ticker: "ABCDEFGHIJ".into(), mint: bs58::encode([0xffu8; 32]).into_string(), burned: u64::MAX, harvested: u64::MAX, fee: 9_999_999_999_999_999_999, signature: bs58::encode([0xffu8; 64]).into_string(), block_time: 253_402_300_799 },
        Receipt { ticker: "S3ED".into(), mint: bs58::encode([1u8; 32]).into_string(), burned: 1, harvested: 40_000, fee: 40_000, signature: bs58::encode([1u8; 64]).into_string(), block_time: 0 },
    ]
    .into_iter()
    .map(|r| {
        let sig = stamper_core::record::solana_signature(&r.signature).unwrap();
        json!({ "receipt": r, "text": r.text().unwrap(), "recordV2": hex::encode(record_v2(&sig)) })
    })
    .collect();
    // unified addresses (ZIP 316, encoded by zcash_address) and the Orchard receiver each carries
    use orchard::keys::{FullViewingKey, Scope, SpendingKey};
    use zcash_address::unified::{self, Encoding};
    use zcash_protocol::consensus::NetworkType;
    let mut addresses = Vec::new();
    for n in [11u8, 12] {
        let sk = Option::<SpendingKey>::from(SpendingKey::from_bytes([n; 32])).unwrap();
        let fvk = FullViewingKey::from(&sk);
        let r = fvk.address_at(0u32, Scope::External).to_raw_address_bytes();
        for (net, name) in [(NetworkType::Main, "mainnet"), (NetworkType::Test, "testnet")] {
            let orchard_only = unified::Address::try_from_items(vec![unified::Receiver::Orchard(r)]).unwrap().encode(&net);
            let with_t = unified::Address::try_from_items(vec![unified::Receiver::P2pkh([n; 20]), unified::Receiver::Orchard(r)]).unwrap().encode(&net);
            let sapling_t = unified::Address::try_from_items(vec![unified::Receiver::P2pkh([n; 20]), unified::Receiver::Sapling([n; 43])]).unwrap().encode(&net);
            addresses.push(json!({ "network": name, "receiver": hex::encode(r), "orchardOnly": orchard_only, "withTransparent": with_t, "noOrchard": sapling_t }));
        }
    }
    json!({ "addresses": addresses, "_comment": "Private stamps (SPEC.md §9): seals of a receiver to a request key, receipt memos and version 2 records. Generated by stamper-core's tests/vectors_private.rs.", "seals": seals, "receipts": receipts })
}

const FILE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../test-vectors/private.json");

#[test]
fn the_vectors_file_matches() {
    let on_disk: Value = serde_json::from_str(&std::fs::read_to_string(FILE).expect("test-vectors/private.json")).unwrap();
    assert_eq!(on_disk, vectors());
}

#[test]
#[ignore]
fn generate() {
    std::fs::write(FILE, serde_json::to_string_pretty(&vectors()).unwrap() + "\n").unwrap();
}
